<?php
define('CLI_SCRIPT', true);
require '/var/www/html/config.php';
require_once $CFG->dirroot . '/course/lib.php';
require_once $CFG->dirroot . '/mod/quiz/locallib.php';
require_once $CFG->dirroot . '/question/editlib.php';
use core_question\local\bank\question_version_status;
\core\session\manager::set_user(get_admin());
$shortname=getenv('PYTHON_COURSE_SHORTNAME')?:'PYAI-INTRO';
$course=$DB->get_record('course',['shortname'=>$shortname],'*',MUST_EXIST);
$language=$shortname==='PYAI-INTRO-JA'?'ja':'en';

function v25_code(string $c):string{return '<pre style="background:#f4f5f7;border:1px solid #d8dce1;padding:1em;overflow:auto"><code>'.s($c).'</code></pre>';}
function v25_q(string $id,string $prompt,array $choices,int $correct,string $explanation):array{return compact('id','prompt','choices','correct','explanation');}
function v25_save(int $cat,int $ctx,string $prefix,array $d,string $lang):stdClass{
    $q=(object)['qtype'=>'multichoice','category'=>$cat.','.$ctx];$a=$f=$r=[];
    foreach($d['choices'] as $i=>[$text,$why]){$a[]=['text'=>$text,'format'=>FORMAT_PLAIN];$f[]=['text'=>'<p>'.s($why).'</p>','format'=>FORMAT_HTML];$r[]=$i===$d['correct']?1.0:0.0;}
    $form=(object)['name'=>$prefix.$d['id'],'category'=>$cat.','.$ctx,'questiontext'=>['text'=>$d['prompt'],'format'=>FORMAT_HTML],
      'generalfeedback'=>['text'=>'<p><strong>'.($lang==='ja'?'学習ポイント：':'Learning point:').'</strong> '.s($d['explanation']).'</p>','format'=>FORMAT_HTML],
      'defaultmark'=>10,'penalty'=>0.3333333,'status'=>question_version_status::QUESTION_STATUS_READY,'idnumber'=>null,'single'=>1,'shuffleanswers'=>1,'answernumbering'=>'abc','showstandardinstruction'=>1,
      'correctfeedback'=>['text'=>$lang==='ja'?'<p>正解です。集計単位、件数、分母、照合を結び付けて進みましょう。</p>':'<p>Correct. Connect grain, count, denominator, and reconciliation.</p>','format'=>FORMAT_HTML],
      'partiallycorrectfeedback'=>['text'=>'','format'=>FORMAT_HTML],'incorrectfeedback'=>['text'=>$lang==='ja'?'<p>結果の一行が何を表し、何を分母にしたかを確認して再挑戦しましょう。</p>':'<p>Check what one result row means and which denominator is used, then retry.</p>','format'=>FORMAT_HTML],
      'shownumcorrect'=>0,'answer'=>$a,'fraction'=>$r,'feedback'=>$f,'hint'=>[]];
    return question_bank::get_qtype('multichoice')->save_question($q,$form);
}
function v25_rename(int $cid,string $table,string $old,string $new):stdClass{global $DB;$r=$DB->get_record($table,['course'=>$cid,'name'=>$new]);if(!$r){$r=$DB->get_record($table,['course'=>$cid,'name'=>$old],'*',MUST_EXIST);$r->name=$new;if(property_exists($r,'timemodified'))$r->timemodified=time();$DB->update_record($table,$r);}return $r;}

if($language==='ja'){
 $oldtopic='3.4 グループ化と要約統計量';$topic='3.4 グループ化と要約統計';
 $summary='<p>明細行をグループ別の意思決定用表へ集約し、粒度、件数、分母、中心、ばらつき、構成比、全体照合を明示します。</p>';
 $oldpage='レッスン10：グループ化と要約統計量';$oldlti='Python Lab 10：グループ化と統計';$oldquiz='理解度チェック：レッスン10 グループ化と要約統計量';
 $pagename='レッスン3.4：グループ化と要約統計';$ltiname='Python Lab 3.4：グループ化と要約統計';$quizname='理解度チェック：3.4 グループ化と要約統計';
 $pageintro='<p>集計前後の一行の意味を定義し、件数、統計量、比率の分母、全体合計を検証します。</p>';
 $quizintro='<p>短い表とコードから、集計粒度、groupby、件数、統計量、分母、複数キー、構成比、照合を確認します。何度でも挑戦でき、最高点が記録されます。</p>';
 $body='<div class="python-sample-lesson"><h2>集計する前に、一行の意味を決める</h2>'
 .'<p>3.3では品質規則を満たす分析用データを作りました。次は24件の明細を、会議や報告で読める少数の行へまとめます。しかし、集計は情報を圧縮するため、何を一行とするかを先に定義しなければなりません。元表の一行はセンター・月・コース、地区別集計の一行は一地区、地区・コース別集計の一行はその組合せです。この単位を粒度と呼びます。</p>'
 .'<h3>groupbyは分割・計算・結合を行う</h3><p><code>groupby("district")</code>は同じ地区の行を分け、各地区へ同じ集計を適用し、結果を結合します。名前付き<code>agg()</code>なら出力列の意味がコードに残ります。<code>reset_index()</code>はグループキーを通常の列へ戻します。</p>'
 .v25_code("district = analysis.groupby(\"district\", dropna=False).agg(\n    centre_months=(\"centre_id\", \"size\"),\n    centres=(\"centre_id\", \"nunique\"),\n    registered_total=(\"registered\", \"sum\"),\n).reset_index()")
 .'<h3>size・count・nuniqueを使い分ける</h3><p><code>size</code>は欠損を含む行数、<code>count</code>は指定列の欠損でない値の数、<code>nunique</code>は異なる値の数です。センター月数、出席報告済み件数、異なるセンター数は同じ「件数」ではありません。列名も質問に合う具体名にします。</p>'
 .'<h3>合計、中心、ばらつきは別の問いに答える</h3><p><code>sum</code>は総量、<code>mean</code>は算術平均、<code>median</code>は並べた中央、<code>min</code>と<code>max</code>は範囲の端、<code>std</code>は平均からの散らばりです。極端な値は平均を動かすため、件数、中央値、最小・最大と一緒に読みます。標準偏差はばらつきの大きさを示しますが、原因を説明するものではありません。</p>'
 .v25_code("analysis.groupby(\"course\")[\"registered\"].agg([\"size\", \"sum\", \"mean\", \"median\", \"min\", \"max\", \"std\"])")
 .'<h3>率は分子と分母を合計してから求める</h3><p>コース全体の修了率は、コースの修了者合計を登録者合計で割ります。各センター月の修了率を単純平均すると、小規模な行と大規模な行へ同じ重みを与えます。これは「典型的なセンター月」を尋ねる値であり、「全登録者のうち何人が修了したか」とは違います。問いに合う分母を文章でも明記します。</p>'
 .v25_code("course = analysis.groupby(\"course\").agg(\n    records=(\"centre_id\", \"size\"),\n    registered=(\"registered\", \"sum\"),\n    completed=(\"completed\", \"sum\"),\n    mean_row_rate=(\"completion_rate\", \"mean\"),\n    material_cost=(\"material_cost\", \"sum\"),\n)\ncourse[\"overall_completion_rate\"] = course[\"completed\"] / course[\"registered\"] * 100\ncourse[\"cost_per_completion\"] = course[\"material_cost\"] / course[\"completed\"]")
 .'<p>練習データのPython Foundationsでは、行別修了率の単純平均は約71.9%、合計修了者290人を合計登録者400人で割った全体修了率は72.5%です。似た値でも定義が違うため、名前と分母を省略してはいけません。</p>'
 .'<h3>複数キーでは比較の階層を保つ</h3><p><code>groupby(["district", "course"])</code>は一地区・一コースを一行にします。地区だけの表とは粒度が違います。粒度の異なる表を、そのまま足したり平均したりしてはいけません。必要なら<code>sort_values()</code>で表示順も明示します。</p>'
 .'<h3>構成比は分母と100%を確認する</h3><p>地区内のコース別登録者構成比なら、各地区・コースの登録者数をその地区の登録者合計で割ります。全体合計を使えば別の問いです。<code>transform("sum")</code>で各行へ地区合計を対応させ、地区ごとの構成比合計が100%になることを確認します。</p>'
 .v25_code("dc[\"district_total\"] = dc.groupby(\"district\")[\"registered\"].transform(\"sum\")\ndc[\"share\"] = dc[\"registered\"] / dc[\"district_total\"] * 100\nprint(dc.groupby(\"district\")[\"share\"].sum())")
 .'<h3>部分集計を明細の全体合計と照合する</h3><p>グループ別の記録数、登録者数、修了者数、教材費を再合計すると、分析用明細の全体と一致するはずです。<code>assert</code>で照合すれば、欠落や二重集計をデータ更新時に検出できます。平均の比較には必ず件数を添え、少数グループの差を原因や優劣の証明として扱いません。</p>'
 .v25_code("assert int(course[\"records\"].sum()) == len(analysis)\nassert course[\"registered\"].sum() == analysis[\"registered\"].sum()\nassert course[\"completed\"].sum() == analysis[\"completed\"].sum()")
 .'<h3>例題から応用へ</h3><p>月別・コース別に、記録数、異なるセンター数、登録者・出席者・修了者合計、全体修了率、教材費合計、一人修了当たり教材費を作ります。各率の分母を書き、行別率平均と比較し、全体合計との照合を追加します。</p>'
 .'<p>集計粒度を定義し、件数の種類と統計量を選び、比率の分子・分母を先に合計し、複数キー、構成比、全体照合を説明できれば、このレッスンの到達点です。</p><p><strong>学習時間の目安：</strong>約3時間</p><p style="display:none">PYAI-V25-LESSON34-FLOW</p></div>';
 $questions=[
 v25_q('L34R-01','<p>元表の一行が「センター・月・コース」の記録です。<code>groupby(["district", "course"])</code>後の一行は何を表しますか。</p>',[['一地区・一コース','正解です。指定したキーの組合せが粒度です。'],['一センターだけ','センターはキーにありません。'],['一か月だけ','月はキーにありません。'],['元表の一行と必ず同じ','複数の明細をまとめます。']],0,'グループキーの一意な組合せが結果の一行です。'),
 v25_q('L34R-02','<p>出席者数に欠損が1件ある10行について、行数と報告済み出席者数を得る組合せはどれですか。</p>',[['attendedのcount=10、size=9','逆です。'],['size=10、attendedのcount=9','正解です。'],['nunique=10だけ','異なる値の数です。'],['sum=10','値の合計で行数ではありません。']],1,'sizeは行、countは欠損でない指定列を数えます。'),
 v25_q('L34R-03','<p>登録者数<code>[20, 22, 24, 100]</code>で、極端な100の影響を平均より受けにくい中心はどれですか。</p>',[['合計','中心ではありません。'],['中央値','正解です。中央二値の平均23です。'],['最大値','端の値です。'],['標準偏差','ばらつきです。']],1,'中央値は順序の中央を使い、極端値の影響が比較的小さい統計量です。'),
 v25_q('L34R-04','<p>標準偏差が大きいことから直接言えることはどれですか。</p>',[['値が平均の周囲に広く散らばっている','正解です。'],['グループ差の原因が判明した','原因は説明しません。'],['平均が必ず誤りである','平均の正誤とは別です。'],['全件が欠損である','欠損を意味しません。']],0,'標準偏差はばらつきを表しますが因果を示しません。'),
 v25_q('L34R-05','<p>2行が登録10・修了10、登録90・修了45です。全登録者の修了率はどれですか。</p>',[['75%：100%と50%の単純平均','行へ同じ重みを与えています。'],['55%：(10+45)/(10+90)','正解です。'],['50%：大きい行だけ','小さい行も含めます。'],['45%：修了者合計だけ','分母がありません。']],1,'全体率は互換性のある分子・分母の合計から求めます。'),
 v25_q('L34R-06','<p>行別率平均と合計比率が異なる主な理由は何ですか。</p>',[['行ごとの分母が違うのに、単純平均は各行へ同じ重みを与えるから','正解です。'],['pandasが常に乱数を使うから','決定的な計算です。'],['中央値と合計が同じだから','関係ありません。'],['groupbyは数値を文字列にするから','通常そのようにはなりません。']],0,'問いが典型的な行か全参加者かで選ぶ率が変わります。'),
 v25_q('L34R-07','<p>地区内コース構成比の正しい分母はどれですか。</p>',[['全地区の登録者合計','全体に対する構成比になります。'],['同じ地区の登録者合計','正解です。'],['コース名の数','人数の構成比になりません。'],['行数だけ','登録者構成比の分母ではありません。']],1,'「地区内」という語が分母の範囲を定めます。'),
 v25_q('L34R-08','<p><code>groupby(["district","course"])</code>の結果と地区だけの結果を比較するときの注意はどれですか。</p>',[['粒度が違うため無条件に足したり平均したりしない','正解です。'],['必ず行数が同じである','通常違います。'],['地区列を削除する','階層が失われます。'],['コース名を数値へ変換する','必要ありません。']],0,'結果一行の意味が違う表は、関係を定義してから結合します。'),
 v25_q('L34R-09','<p>地区内の構成比を計算した後の直接的な検証はどれですか。</p>',[['地区ごとの構成比合計が約100%になる','正解です。'],['全行の平均が必ず50になる','その保証はありません。'],['最大値が登録者合計になる','単位が違います。'],['標準偏差が0になる','複数比率は異なり得ます。']],0,'同じ分母で分割した構成比はグループ内で100%へ戻ります。'),
 v25_q('L34R-10','<p>グループ別登録者合計を作った後、取りこぼしを直接確認する方法はどれですか。</p>',[['グループ合計の再合計を分析用明細の登録者合計と比較する','正解です。'],['表の色を変える','件数を検証しません。'],['最小グループを削除する','照合ではありません。'],['平均だけ表示する','総量の欠落を確認できません。']],0,'部分合計を元の分析対象全体へ照合します。')];
}else{
 $oldtopic='3.4 Grouping and summary statistics';$topic='3.4 Grouping and summary statistics';
 $summary='<p>Aggregate detail into decision-sized group tables while making grain, counts, denominators, centre, spread, proportions, and reconciliation explicit.</p>';
 $oldpage='Lesson 10: Grouping and summary statistics';$oldlti='Python Lab 10: Grouping and statistics';$oldquiz='Knowledge check: Lesson 10: Grouping and summary statistics';
 $pagename='Lesson 3.4: Grouping and summary statistics';$ltiname='Python Lab 3.4: Grouping and summary statistics';$quizname='Knowledge check: 3.4 Grouping and summary statistics';
 $pageintro='<p>Define result grain and verify counts, statistics, rate denominators, and reconciliation.</p>';$quizintro='<p>Use short tables and code to check grain, groupby, counts, statistics, denominators, multiple keys, proportions, and reconciliation. Retry as needed; the highest score is kept.</p>';
 $body='<div class="python-sample-lesson"><h2>Define what one result row means before aggregation</h2><p>Lesson 3.3 produced analysis-ready detail. Aggregation now compresses those rows into a report. One detail row means centre-month-course; one district summary row means a district; one district-course row means that pair. Define this grain first or even a correct number may be impossible to explain.</p>'
 .'<h3>groupby splits, applies, and combines</h3><p><code>groupby("district")</code> splits matching rows, applies the same named aggregations, and combines results. Named <code>agg()</code> records output meaning; <code>reset_index()</code> restores group keys as ordinary columns.</p>'.v25_code("district = analysis.groupby(\"district\", dropna=False).agg(\n centre_months=(\"centre_id\",\"size\"), centres=(\"centre_id\",\"nunique\"), registered_total=(\"registered\",\"sum\")\n).reset_index()")
 .'<h3>Distinguish size, count, and nunique</h3><p><code>size</code> counts rows including missing values, <code>count</code> counts non-missing values in a selected column, and <code>nunique</code> counts distinct values. Centre-month records, reported attendance values, and distinct centres are different measures.</p>'
 .'<h3>Totals, centre, and spread answer different questions</h3><p><code>sum</code> measures volume, <code>mean</code> arithmetic centre, <code>median</code> the middle ordered value, <code>min</code> and <code>max</code> endpoints, and <code>std</code> spread around the mean. Extremes can pull the mean, so show count, median, and range. Standard deviation does not explain causes.</p>'.v25_code("analysis.groupby(\"course\")[\"registered\"].agg([\"size\",\"sum\",\"mean\",\"median\",\"min\",\"max\",\"std\"])")
 .'<h3>Aggregate compatible numerators and denominators before a rate</h3><p>Overall course completion is total completed divided by total registered. A simple mean of centre-month rates gives a small and a large record equal weight. It answers about a typical record, not all registered learners. State the denominator in words.</p>'.v25_code("course = analysis.groupby(\"course\").agg(records=(\"centre_id\",\"size\"),registered=(\"registered\",\"sum\"),completed=(\"completed\",\"sum\"),mean_row_rate=(\"completion_rate\",\"mean\"),material_cost=(\"material_cost\",\"sum\"))\ncourse[\"overall_completion_rate\"] = course[\"completed\"] / course[\"registered\"] * 100\ncourse[\"cost_per_completion\"] = course[\"material_cost\"] / course[\"completed\"]")
 .'<p>For Python Foundations in the practice data, the simple mean row rate is about 71.9%, while 290 total completions divided by 400 total registrations is 72.5%. Similar values still have different definitions.</p>'
 .'<h3>Multiple keys preserve hierarchy</h3><p><code>groupby(["district","course"])</code> creates one row per pair. This differs from district-only grain. Do not add or average incompatible grains without defining their relationship.</p>'
 .'<h3>State the proportion denominator and check 100%</h3><p>Course share within a district divides district-course registrations by that district total. The grand total answers another question. <code>transform("sum")</code> aligns denominators, and within-district shares should sum to 100%.</p>'.v25_code("dc[\"district_total\"] = dc.groupby(\"district\")[\"registered\"].transform(\"sum\")\ndc[\"share\"] = dc[\"registered\"] / dc[\"district_total\"] * 100")
 .'<h3>Reconcile grouped totals with detail</h3><p>Grouped record, registered, completed, and material-cost totals must sum back to analysis detail. Assertions expose omitted or double-counted data. Attach counts to averages and do not interpret a small-group difference as proof of cause or superiority.</p>'.v25_code("assert int(course[\"records\"].sum()) == len(analysis)\nassert course[\"registered\"].sum() == analysis[\"registered\"].sum()\nassert course[\"completed\"].sum() == analysis[\"completed\"].sum()")
 .'<h3>From worked example to transfer</h3><p>By month and course, calculate record count, distinct centres, registered, attended and completed totals, overall completion rate, material cost, and cost per completion. State denominators, compare with mean row rate, reconcile grand totals, and identify a small-count comparison.</p>'
 .'<p>You have reached the lesson goal when you can define grain, select count and summary functions, aggregate rate components, group by multiple keys, calculate proportions, and reconcile the result.</p><p><strong>Estimated study time:</strong> about 3 hours</p><p style="display:none">PYAI-V25-LESSON34-FLOW</p></div>';
 $questions=[
 v25_q('L34R-01','<p>Source grain is centre-month-course. After <code>groupby(["district","course"])</code>, what does one row mean?</p>',[['One district-course pair','Correct.'],['One centre only','Centre is not a key.'],['One month only','Month is not a key.'],['Always one source row','Rows are aggregated.']],0,'A unique key combination defines result grain.'),
 v25_q('L34R-02','<p>Ten rows contain one missing attendance. Which result is correct?</p>',[['attendance count=10, size=9','Reversed.'],['size=10, attendance count=9','Correct.'],['nunique must be 10','It counts distinct values.'],['sum must be 10','It sums values.']],1,'size counts rows; count excludes missing values in its column.'),
 v25_q('L34R-03','<p>For <code>[20,22,24,100]</code>, which centre is less affected by 100 than the mean?</p>',[['Sum','Not a centre.'],['Median','Correct: it is 23.'],['Maximum','An endpoint.'],['Standard deviation','Spread.']],1,'Median is based on ordered position.'),
 v25_q('L34R-04','<p>What does a large standard deviation directly indicate?</p>',[['Values are widely spread around the mean','Correct.'],['The cause of a group difference','It does not establish cause.'],['The mean is wrong','Not necessarily.'],['All values are missing','No.']],0,'Standard deviation measures spread, not cause.'),
 v25_q('L34R-05','<p>Rows are 10 registered/10 completed and 90/45. What is completion among all registered learners?</p>',[['75%, the mean of 100% and 50%','Equal row weighting.'],['55%, (10+45)/(10+90)','Correct.'],['50%, using only the large row','Both rows count.'],['45%, completed total alone','Missing denominator.']],1,'Aggregate compatible numerator and denominator.'),
 v25_q('L34R-06','<p>Why can mean row rate differ from ratio of totals?</p>',[['Rows have different denominators but the mean weights rows equally','Correct.'],['pandas uses randomness','No.'],['Median equals total','No.'],['groupby changes numbers to text','No.']],0,'The two statistics answer different questions.'),
 v25_q('L34R-07','<p>What denominator gives course registration share within a district?</p>',[['Grand total registration','That is share of all data.'],['Registration total for that district','Correct.'],['Number of course names','Wrong unit.'],['Row count only','Wrong denominator.']],1,'Within-district defines denominator scope.'),
 v25_q('L34R-08','<p>What matters when comparing district-course and district-only summaries?</p>',[['They have different grains and cannot be combined blindly','Correct.'],['They always have equal rows','No.'],['Delete district first','Loses hierarchy.'],['Convert course to a number','Unnecessary.']],0,'Define relationships between grains before combining.'),
 v25_q('L34R-09','<p>What directly validates within-district course shares?</p>',[['Shares sum to about 100% in each district','Correct.'],['All means equal 50','No.'],['Maximum equals registration total','Different units.'],['Standard deviation is zero','Not required.']],0,'Parts sharing one denominator sum to the whole.'),
 v25_q('L34R-10','<p>How do you check no registrations were lost in grouping?</p>',[['Compare sum of group registration totals with detail registration total','Correct.'],['Change chart colour','No check.'],['Delete the smallest group','Not reconciliation.'],['Display only means','Does not check volume.']],0,'Reconcile partial totals with source analysis detail.')];
}

$sub=$DB->get_record('subsection',['course'=>$course->id,'name'=>$topic]);if(!$sub){$sub=$DB->get_record('subsection',['course'=>$course->id,'name'=>$oldtopic],'*',MUST_EXIST);$sub->name=$topic;$sub->timemodified=time();$DB->update_record('subsection',$sub);}
$sec=$DB->get_record('course_sections',['course'=>$course->id,'component'=>'mod_subsection','itemid'=>$sub->id],'*',MUST_EXIST);course_update_section($course,$sec,['name'=>$topic,'summary'=>$summary,'summaryformat'=>FORMAT_HTML,'visible'=>1]);
$page=v25_rename($course->id,'page',$oldpage,$pagename);$lti=v25_rename($course->id,'lti',$oldlti,$ltiname);$quiz=v25_rename($course->id,'quiz',$oldquiz,$quizname);
$page->intro=$pageintro;$page->introformat=FORMAT_HTML;$page->content=$body;$page->contentformat=FORMAT_HTML;$page->timemodified=time();$DB->update_record('page',$page);
$path=$language==='ja'?'/ja/10_grouping_statistics.ipynb':'/10_grouping_statistics.ipynb';$url=preg_replace('~/(?:ja/)?10_grouping_statistics\.ipynb$~',$path,$lti->toolurl);if(!$url||($url===$lti->toolurl&&!str_ends_with($lti->toolurl,$path)))throw new RuntimeException('Cannot update LTI URL');$lti->toolurl=$url;$lti->intro=$language==='ja'?'<p>集計粒度、分母、件数、部分合計の照合をNotebookへ記録します。</p>':'<p>Record grain, denominators, counts, and reconciliation in the notebook.</p>';$lti->introformat=FORMAT_HTML;$lti->timemodified=time();$DB->update_record('lti',$lti);
$removed=(int)$DB->count_records('quiz_attempts',['quiz'=>$quiz->id]);if($removed)quiz_delete_all_attempts($quiz);$structure=\mod_quiz\structure::create_for_quiz(\mod_quiz\quiz_settings::create($quiz->id));foreach(array_reverse($structure->get_slots()) as $slot)$structure->remove_slot($slot->slot);
$quiz->intro=$quizintro;$quiz->introformat=FORMAT_HTML;$quiz->attempts=0;$quiz->grademethod=QUIZ_GRADEHIGHEST;$quiz->grade=100;$quiz->questionsperpage=10;$quiz->timemodified=time();$DB->update_record('quiz',$quiz);
$ctx=context_course::instance($course->id);$cat=$DB->get_record('question_categories',['contextid'=>$ctx->id,'name'=>'Python course checks']);if(!$cat){$cats=$DB->get_records('question_categories',['contextid'=>$ctx->id],'id ASC');$cat=reset($cats);}foreach($questions as $q){$saved=v25_save($cat->id,$ctx->id,$shortname.' v25: ',$q,$language);quiz_add_quiz_question($saved->id,$quiz,0,10);}$DB->set_field('quiz_slots','maxmark',10,['quizid'=>$quiz->id]);\mod_quiz\quiz_settings::create($quiz->id)->get_grade_calculator()->recompute_quiz_sumgrades();
$pcm=get_coursemodule_from_instance('page',$page->id,$course->id,false,MUST_EXIST);$lcm=get_coursemodule_from_instance('lti',$lti->id,$course->id,false,MUST_EXIST);$qcm=get_coursemodule_from_instance('quiz',$quiz->id,$course->id,false,MUST_EXIST);$ids=[(int)$pcm->id,(int)$lcm->id,(int)$qcm->id];$sec->sequence=implode(',',$ids);$DB->update_record('course_sections',$sec);foreach($ids as $id)$DB->set_field('course_modules','section',$sec->id,['id'=>$id]);rebuild_course_cache($course->id,true);
echo json_encode(['courseid'=>(int)$course->id,'shortname'=>$shortname,'topic'=>$topic,'pageid'=>(int)$page->id,'quizid'=>(int)$quiz->id,'ltiid'=>(int)$lti->id,'questions'=>count($questions),'attempts_removed'=>$removed,'lti_path'=>$path,'marker'=>'PYAI-V25-LESSON34-FLOW'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;
