<?php
define('CLI_SCRIPT',true);require '/var/www/html/config.php';require_once $CFG->dirroot.'/course/lib.php';require_once $CFG->dirroot.'/mod/quiz/locallib.php';require_once $CFG->dirroot.'/question/editlib.php';use core_question\local\bank\question_version_status;\core\session\manager::set_user(get_admin());
$sn=getenv('PYTHON_COURSE_SHORTNAME')?:'PYAI-INTRO';$course=$DB->get_record('course',['shortname'=>$sn],'*',MUST_EXIST);$lang=$sn==='PYAI-INTRO-JA'?'ja':'en';
function v26code($c){return '<pre style="background:#f4f5f7;border:1px solid #d8dce1;padding:1em;overflow:auto"><code>'.s($c).'</code></pre>';}
function v26q($id,$p,$c,$ok,$e){return compact('id','p','c','ok','e');}
function v26save($cat,$ctx,$prefix,$d,$lang){$q=(object)['qtype'=>'multichoice','category'=>"$cat,$ctx"];$a=$f=$r=[];foreach($d['c'] as $i=>[$t,$w]){$a[]=['text'=>$t,'format'=>FORMAT_PLAIN];$f[]=['text'=>'<p>'.s($w).'</p>','format'=>FORMAT_HTML];$r[]=$i===$d['ok']?1.0:0.0;}$form=(object)['name'=>$prefix.$d['id'],'category'=>"$cat,$ctx",'questiontext'=>['text'=>$d['p'],'format'=>FORMAT_HTML],'generalfeedback'=>['text'=>'<p><strong>'.($lang==='ja'?'学習ポイント：':'Learning point:').'</strong> '.s($d['e']).'</p>','format'=>FORMAT_HTML],'defaultmark'=>10,'penalty'=>.3333333,'status'=>question_version_status::QUESTION_STATUS_READY,'idnumber'=>null,'single'=>1,'shuffleanswers'=>1,'answernumbering'=>'abc','showstandardinstruction'=>1,'correctfeedback'=>['text'=>$lang==='ja'?'<p>正解です。図の選択、数値、範囲、限界を結び付けましょう。</p>':'<p>Correct. Connect chart choice, numbers, scope, and limitation.</p>','format'=>FORMAT_HTML],'partiallycorrectfeedback'=>['text'=>'','format'=>FORMAT_HTML],'incorrectfeedback'=>['text'=>$lang==='ja'?'<p>問い、描画する一行の意味、軸と分母を確認して再挑戦しましょう。</p>':'<p>Check the question, plotted grain, axes, and denominator, then retry.</p>','format'=>FORMAT_HTML],'shownumcorrect'=>0,'answer'=>$a,'fraction'=>$r,'feedback'=>$f,'hint'=>[]];return question_bank::get_qtype('multichoice')->save_question($q,$form);}
function v26rename($cid,$table,$old,$new){global $DB;$r=$DB->get_record($table,['course'=>$cid,'name'=>$new]);if(!$r){$r=$DB->get_record($table,['course'=>$cid,'name'=>$old],'*',MUST_EXIST);$r->name=$new;if(property_exists($r,'timemodified'))$r->timemodified=time();$DB->update_record($table,$r);}return $r;}
if($lang==='ja'){
$topic='4.1 可視化と根拠';$oldtopic=$topic;$oldpage='レッスン11：可視化と根拠';$oldlti='Python Lab 11：可視化と根拠';$oldquiz='理解度チェック：レッスン11 可視化と根拠';$pn='レッスン4.1：可視化と根拠';$ln='Python Lab 4.1：可視化と根拠';$qn='理解度チェック：4.1 可視化と根拠';
$summary='<p>問いに合う集計表とグラフを選び、軸、単位、件数、範囲、数値、限界を示して観察可能な根拠を伝えます。</p>';$pi='<p>問いと描画粒度を定義してから図を選び、元表と数値を照合して根拠文を書きます。</p>';$qi='<p>棒・折れ線・散布・ヒストグラム、軸、単位、尺度、標本数、因果、根拠文を確認します。何度でも挑戦でき、最高点が記録されます。</p>';
$body='<div class="python-sample-lesson"><h2>グラフを選ぶ前に、問いと描画する一行の意味を決める</h2><p>4.1では、3.4で作った集計表を人が比較できる形にします。グラフは飾りではありません。カテゴリ比較ならカテゴリ別、時系列なら月別へ先に集約し、描画する表の数値を確認してから図を作ります。明細を無条件に描くと、問いと異なる重みや重複を持ち込みます。</p>'
.'<h3>棒グラフはカテゴリの大きさを比較する</h3><p>少数のコース別修了率には棒グラフが適します。修了者合計÷登録者合計で率を求め、意味のある順に並べます。棒の長さが量を表すため、通常は0を起点にし、割合なら0〜100%を基準にします。70%から始めると72%と74%の差を誇張します。</p>'.v26code("fig, ax = plt.subplots()\nax.barh(course[\"course\"], course[\"completion_rate\"])\nax.set(xlabel=\"Completion rate (%)\", title=\"Overall completion rate by course\")\nax.set_xlim(0, 100)")
.'<h3>折れ線グラフは時間順の変化を示す</h3><p>月は日時へ変換して並べます。欠けた月がある場合、そのまま線で結ぶと連続観測のように見えるため、期待する月一覧へ再配置して欠損を示します。順序のないコース名を折れ線で結ぶと、存在しない途中の変化を暗示します。</p>'
.'<h3>散布図は二つの数値の関係を調べる</h3><p>一記録の修了者数と教材費のような二数値を点で対応させます。まとまりや外れを観察できますが、関連があっても因果関係は証明しません。センター規模、月、コースなど別要因が両方へ影響する可能性があります。</p>'
.'<h3>ヒストグラムは一つの数値の分布を示す</h3><p>ヒストグラムは連続する数値区間ごとの件数、棒グラフは独立カテゴリの量を示します。ビン幅で見え方が変わるため複数を試し、標本数<code>n</code>も示します。少ない点から滑らかな分布を断定しません。</p>'
.'<h3>タイトル、軸、単位、凡例、色を意味に合わせる</h3><p>タイトルには比較対象、軸には変数名と単位を記します。複数系列だけ凡例を付け、色だけに意味を依存せず、コントラストや直接ラベルを使います。3Dや過剰な装飾、面積で量を誇張する表現は避けます。</p>'
.'<h3>尺度、並び順、欠損を隠さない</h3><p>軸範囲と並び順は差の印象を変えます。狭い軸で小変化を示す場合は範囲を明示し、差の絶対値も文章へ書きます。並べ替え規則を一貫させ、欠損を0へ置き換えて線をつなげません。</p>'
.'<h3>グラフの元表を照合する</h3><p>描画前に表を表示し、登録者・修了者合計が分析用明細と一致することを<code>assert</code>で確認します。グラフは元データの品質や計算を自動検証しません。Notebookへ集計と描画コードを残し、必要なら<code>savefig()</code>で同じ画像を再生成します。</p>'.v26code("assert course[\"registered\"].sum() == analysis[\"registered\"].sum()\nassert course[\"completed\"].sum() == analysis[\"completed\"].sum()\n# fig.savefig(\"completion-rate-by-course.png\", dpi=150, bbox_inches=\"tight\")")
.'<h3>根拠文は観察・数値・範囲・限界を含める</h3><p>「Python Foundationsの全体修了率は72.5%、Digital Skillsは約73.1%で、差は約0.6ポイントだった」と観察を数値で支えます。続けて「分析可能な22センター月に限られ、参加者構成や難易度を調整していないため、原因や優劣は判断できない」と範囲と限界を書きます。図だけから因果を断定しません。</p>'
.'<h3>例題から応用へ</h3><p>月別登録者数の折れ線、コース別一人修了当たり教材費の棒、登録者数と修了率の散布図を作ります。各図に問い、描画粒度、軸、単位、件数を示し、一図について観察・数値・範囲・限界の4文を書きます。誤解を招く軸範囲も作り、採用しない理由を説明します。</p><p>問いに合う図を選び、集計後に描き、尺度と欠損を隠さず、数値と限界を伴う根拠文を書ければ到達です。</p><p><strong>学習時間の目安：</strong>約3時間</p><p style="display:none">PYAI-V26-LESSON41-FLOW</p></div>';
$qs=[
v26q('L41R-01','<p>4コースの全体修了率を比較するのに最も適した図はどれですか。</p>',[['棒グラフ','正解です。少数カテゴリの量を比較します。'],['順序を暗示する折れ線','コース間に連続順序はありません。'],['ヒストグラム','一変数の分布用です。'],['無加工の全明細散布図','問いの粒度と違います。']],0,'問いの構造に合う図を選びます。'),
v26q('L41R-02','<p>月別推移の前処理として重要なのはどれですか。</p>',[['月を日時に変換して時間順に並べ、欠けた月を確認する','正解です。'],['月名をランダム順にする','推移を壊します。'],['欠損月を必ず0とする','未観測と0は違います。'],['コース名を線で結ぶ','時間ではありません。']],0,'時間順と観測欠落を明示します。'),
v26q('L41R-03','<p>修了者数と教材費の関係を一記録ごとに見る図はどれですか。</p>',[['散布図','正解です。'],['円グラフ','部分構成用です。'],['ヒストグラム','一変数です。'],['一つの棒','関係を示せません。']],0,'散布図は二つの量的変数を対応させます。'),
v26q('L41R-04','<p>ヒストグラムのビン幅を変えると何が起こりますか。</p>',[['分布の見え方が変わるため複数幅と件数を確認する','正解です。'],['元データが自動修正される','されません。'],['カテゴリ名が時間順になる','無関係です。'],['因果関係が証明される','されません。']],0,'区間設定は分布の見え方に影響します。'),
v26q('L41R-05','<p>72%と74%の棒を70%から始める主な問題は何ですか。</p>',[['2ポイントの差を視覚的に誇張する','正解です。'],['割合を数値にできない','できます。'],['色が使えない','無関係です。'],['標本数が必ず増える','増えません。']],0,'棒の長さ比較では0起点が基準です。'),
v26q('L41R-06','<p>色覚に依存しにくい表示はどれですか。</p>',[['色だけで系列を区別する','識別できない場合があります。'],['十分なコントラストに加え線種や直接ラベルも使う','正解です。'],['すべてを薄い同色にする','区別困難です。'],['3D効果を付ける','歪みます。']],1,'色以外の手掛かりも使います。'),
v26q('L41R-07','<p>グラフ作成前の直接的な検証はどれですか。</p>',[['描画用集計表の合計を分析用明細と照合する','正解です。'],['画像の色だけ確認する','数値検証ではありません。'],['タイトルを削除する','意味が不明になります。'],['欠損を隠す','品質問題を隠します。']],0,'描画元の表と数値を先に検証します。'),
v26q('L41R-08','<p>新施策後に修了率が上がったグラフだけから言えることは何ですか。</p>',[['観測データ上の関連であり、施策が原因とはまだ言えない','正解です。'],['施策が必ず全改善を起こした','他要因があります。'],['データが自動的に正しい','図は検証しません。'],['何も観察できない','変化は記述できます。']],0,'観察と因果を分けます。'),
v26q('L41R-09','<p>根拠文として最も強いものはどれですか。</p>',[['Aが良かった','数値と範囲がありません。'],['Aは72.5%、Bは73.1%で差0.6ポイント。22記録に限られ原因は判断できない','正解です。'],['グラフが美しいので正しい','見栄えは根拠でありません。'],['Bが原因でAが下がった','因果根拠がありません。']],1,'観察、数値、範囲、限界を含めます。'),
v26q('L41R-10','<p>再現可能な成果物として最も適切なのはどれですか。</p>',[['画像だけ','計算条件が分かりません。'],['集計・描画コード、元表確認、根拠文を含むNotebookと必要な保存画像','正解です。'],['口頭の印象だけ','再検証できません。'],['軸を消したスクリーンショット','意味を失います。']],1,'図を再生成し検証できる経路を残します。')];
}else{
$topic='4.1 Visualisation and evidence';$oldtopic=$topic;$oldpage='Lesson 11: Visualisation and evidence';$oldlti='Python Lab 11: Visualisation and evidence';$oldquiz='Knowledge check: Lesson 11: Visualisation and evidence';$pn='Lesson 4.1: Visualisation and evidence';$ln='Python Lab 4.1: Visualisation and evidence';$qn='Knowledge check: 4.1 Visualisation and evidence';$summary='<p>Choose a chart from the question and communicate evidence with axes, units, counts, scale, numbers, scope, and limitation.</p>';$pi='<p>Define question and plotted grain, verify the chart table, then communicate evidence.</p>';$qi='<p>Check bars, lines, scatter, histograms, labels, scale, n, causation, and evidence writing. Retry as needed; highest score is kept.</p>';
$body='<div class="python-sample-lesson"><h2>Define the question and plotted grain before chart type</h2><p>A chart is evidence communication, not decoration. Aggregate detail to category grain for comparison or ordered time grain for trends, inspect the plotted table, then draw.</p><h3>Bars compare category magnitudes</h3><p>Use bars for a few unordered categories. Compute overall rates from total completed and registered, sort deliberately, and normally start the length axis at zero. A 70% baseline exaggerates 72% versus 74%.</p>'.v26code("ax.barh(course[\"course\"],course[\"completion_rate\"]); ax.set(xlabel=\"Completion rate (%)\"); ax.set_xlim(0,100)")
.'<h3>Lines show ordered time change</h3><p>Convert month to date, sort chronologically, and expose missing periods. Joining only observed months can imply continuous observation. Lines across unordered categories invent an in-between path.</p><h3>Scatter plots examine two quantitative variables</h3><p>Each point links two values from one record. Clusters and unusual points are visible, but association does not establish causation; centre size, month, or course may affect both.</p><h3>Histograms show one quantitative distribution</h3><p>Histograms count adjacent numeric bins; bars compare separate categories. Bin width changes the visible pattern, so inspect alternatives and state sample size.</p><h3>Label title, axes, units, legend, and colour</h3><p>Name the comparison and units. Use legends only for multiple series, do not rely on colour alone, and use contrast, line style, or direct labels. Avoid 3D and decorative area distortion.</p><h3>Disclose scale, order, and missingness</h3><p>Axis range and ordering alter impressions. If a narrow range is useful for a line, disclose it and state the absolute difference. Apply consistent order and never silently convert missing periods to zero.</p><h3>Reconcile the plotted table</h3><p>Display the chart table and assert that totals match analysis detail. A chart does not validate its source. Keep aggregation and plotting code, and optionally save a reproducible image with <code>savefig()</code>.</p>'.v26code("assert course[\"registered\"].sum()==analysis[\"registered\"].sum()\nassert course[\"completed\"].sum()==analysis[\"completed\"].sum()")
.'<h3>Write observation, numbers, scope, and limitation</h3><p>“Overall completion was 72.5% for Python Foundations and about 73.1% for Digital Skills, a difference of about 0.6 percentage points.” Then state that only 22 analysis-ready centre-months are included and learner mix and course difficulty are uncontrolled, so cause or superiority is not established.</p><h3>From worked example to transfer</h3><p>Create monthly registrations as a line, course cost per completion as bars, and registrations versus completion rate as scatter. State question, grain, axes, units, and n. Write four evidence sentences and reject one misleading scale version.</p><p>You have reached the goal when chart choice follows the question, plotted data reconciles, scale and missingness are visible, and claims include numbers and limitations.</p><p><strong>Estimated study time:</strong> about 3 hours</p><p style="display:none">PYAI-V26-LESSON41-FLOW</p></div>';
$qs=[v26q('L41R-01','<p>Best chart for overall completion across four courses?</p>',[['Bar chart','Correct.'],['Unordered line','Implies order.'],['Histogram','Distribution.'],['Raw scatter','Wrong grain.']],0,'Bars compare categories.'),v26q('L41R-02','<p>Essential preparation for a monthly trend?</p>',[['Parse and sort dates; expose missing months','Correct.'],['Randomise months','Wrong.'],['Fill every missing month with zero','Missing is not zero.'],['Join course names','Not time.']],0,'Preserve chronology and gaps.'),v26q('L41R-03','<p>Chart for completions versus material cost per record?</p>',[['Scatter','Correct.'],['Pie','Composition.'],['Histogram','One variable.'],['One bar','No relationship.']],0,'Scatter links two quantities.'),v26q('L41R-04','<p>What does changing histogram bin width do?</p>',[['Changes visible distribution pattern; inspect alternatives and n','Correct.'],['Repairs source','No.'],['Orders categories','No.'],['Proves cause','No.']],0,'Bins affect appearance.'),v26q('L41R-05','<p>Problem with bars for 72% and 74% starting at 70%?</p>',[['Exaggerates a two-point difference','Correct.'],['Percent cannot be plotted','False.'],['Colour fails','Unrelated.'],['n increases','No.']],0,'Bar length needs an honest baseline.'),v26q('L41R-06','<p>Accessible series distinction?</p>',[['Colour only','Insufficient.'],['Contrast plus line style or direct labels','Correct.'],['All pale same colour','Hard to distinguish.'],['3D','Distorts.']],1,'Use non-colour cues.'),v26q('L41R-07','<p>Direct pre-plot validation?</p>',[['Reconcile plotted-table totals with detail','Correct.'],['Inspect colour only','No.'],['Remove title','No.'],['Hide missingness','No.']],0,'Verify plotted data.'),v26q('L41R-08','<p>Rate rose after a programme. What can chart alone establish?</p>',[['Observed association, not necessarily causation','Correct.'],['Programme caused all change','Unsupported.'],['Source is automatically valid','No.'],['Nothing can be observed','Change can be described.']],0,'Separate observation and cause.'),v26q('L41R-09','<p>Strongest evidence statement?</p>',[['A was good','No numbers.'],['A 72.5%, B 73.1%, difference 0.6 points; 22 records and no causal claim','Correct.'],['Pretty chart means correct','No.'],['B caused A','Unsupported.']],1,'Include observation, numbers, scope, limitation.'),v26q('L41R-10','<p>Most reproducible deliverable?</p>',[['Image only','No calculations.'],['Notebook with aggregation, plotting, table checks, evidence text, and optional saved image','Correct.'],['Oral impression','Not reproducible.'],['Screenshot without axes','No meaning.']],1,'Preserve the path from data to claim.')];}
$sub=$DB->get_record('subsection',['course'=>$course->id,'name'=>$topic]);if(!$sub){$sub=$DB->get_record('subsection',['course'=>$course->id,'name'=>$oldtopic],'*',MUST_EXIST);}$sec=$DB->get_record('course_sections',['course'=>$course->id,'component'=>'mod_subsection','itemid'=>$sub->id],'*',MUST_EXIST);course_update_section($course,$sec,['name'=>$topic,'summary'=>$summary,'summaryformat'=>FORMAT_HTML,'visible'=>1]);$p=v26rename($course->id,'page',$oldpage,$pn);$l=v26rename($course->id,'lti',$oldlti,$ln);$q=v26rename($course->id,'quiz',$oldquiz,$qn);$p->intro=$pi;$p->introformat=FORMAT_HTML;$p->content=$body;$p->contentformat=FORMAT_HTML;$p->timemodified=time();$DB->update_record('page',$p);$path=$lang==='ja'?'/ja/11_visualisation_evidence.ipynb':'/11_visualisation_evidence.ipynb';$url=preg_replace('~/(?:ja/)?11_visualisation_evidence\.ipynb$~',$path,$l->toolurl);if(!$url||($url===$l->toolurl&&!str_ends_with($l->toolurl,$path)))throw new RuntimeException('LTI URL');$l->toolurl=$url;$l->intro=$lang==='ja'?'<p>描画表、図、数値、範囲、限界をNotebookへ残します。</p>':'<p>Keep plotted table, chart, numbers, scope, and limitation in the notebook.</p>';$l->introformat=FORMAT_HTML;$l->timemodified=time();$DB->update_record('lti',$l);
$removed=(int)$DB->count_records('quiz_attempts',['quiz'=>$q->id]);if($removed)quiz_delete_all_attempts($q);$st=\mod_quiz\structure::create_for_quiz(\mod_quiz\quiz_settings::create($q->id));foreach(array_reverse($st->get_slots()) as $slot)$st->remove_slot($slot->slot);$q->intro=$qi;$q->introformat=FORMAT_HTML;$q->attempts=0;$q->grademethod=QUIZ_GRADEHIGHEST;$q->grade=100;$q->questionsperpage=10;$q->timemodified=time();$DB->update_record('quiz',$q);$ctx=context_course::instance($course->id);$cat=$DB->get_record('question_categories',['contextid'=>$ctx->id,'name'=>'Python course checks']);if(!$cat){$cats=$DB->get_records('question_categories',['contextid'=>$ctx->id],'id ASC');$cat=reset($cats);}foreach($qs as $x){$saved=v26save($cat->id,$ctx->id,$sn.' v26: ',$x,$lang);quiz_add_quiz_question($saved->id,$q,0,10);}$DB->set_field('quiz_slots','maxmark',10,['quizid'=>$q->id]);\mod_quiz\quiz_settings::create($q->id)->get_grade_calculator()->recompute_quiz_sumgrades();$pcm=get_coursemodule_from_instance('page',$p->id,$course->id,false,MUST_EXIST);$lcm=get_coursemodule_from_instance('lti',$l->id,$course->id,false,MUST_EXIST);$qcm=get_coursemodule_from_instance('quiz',$q->id,$course->id,false,MUST_EXIST);$ids=[(int)$pcm->id,(int)$lcm->id,(int)$qcm->id];$sec->sequence=implode(',',$ids);$DB->update_record('course_sections',$sec);foreach($ids as $id)$DB->set_field('course_modules','section',$sec->id,['id'=>$id]);rebuild_course_cache($course->id,true);echo json_encode(['courseid'=>(int)$course->id,'shortname'=>$sn,'topic'=>$topic,'pageid'=>(int)$p->id,'quizid'=>(int)$q->id,'ltiid'=>(int)$l->id,'questions'=>count($qs),'attempts_removed'=>$removed,'lti_path'=>$path,'marker'=>'PYAI-V26-LESSON41-FLOW'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;
